name: Build Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Set VCPKG_ROOT
      run: echo "VCPKG_ROOT=${env:ProgramFiles(x86)}\\vcpkg" >> $env:GITHUB_ENV

    - name: Configure (CMake preset x64-release)
      run: cmake --preset x64-release

    - name: Build
      run: cmake --build --preset x64-release --verbose
