name: Build Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSVC 
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Set VCPKG_ROOT
      run: echo "VCPKG_ROOT=C:\\vcpkg" >> $env:GITHUB_ENV

    - name: Configure
      run: cmake --preset x64-release

    - name: Build
      run: cmake --build out/build/x64-release --verbose

    - name: EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TwentyFortyEight
        path: out/build/x64-release/TwentyFortyEight.exe
